name: 'Autobump patch version and tag'
description: 'Takes repo sha and creates a new tag with increased patch version. Excepts SemVer X.Y.Z'
inputs:
  GITHUB_TOKEN:  # id of input
    description: 'Github Token for authentication'
    required: true
  repositoryName: # id of input
    description: 'Repository Name for tag lookup'
    required: true
  repositoryOwner: # id of input
    description: 'owner of the repository'
    required: true
  sha: # id of input
    description: 'sha id for tag creation'
    required: true

outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'