name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  GITHUB_TOKEN:  # id of input
    description: 'Github Token for authentication'
    required: true
  repositoryName: # id of input
    description: 'Repository Name for tag lookup'
    required: true
  sha: # id of input
    description: 'sha id for tag creation'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'