on: [push]

jobs:
  autoBump_tag:
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Increment SemVer Patch Version and Tag
        uses: ./ # Uses an action in the root directory
        id: createTag
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          repositoryName: ${{ github.event.repository.name }}
          sha: ${{ github.sha }}
          repositoryOwner: ${{ github.repository_owner }}
      # Use the output from the `createTag` step
      - name: Get the output tag
        run: echo "The tag was ${{ steps.createTag.outputs.newTag }}"
  
  job-c:
    name: job-c
    runs-on: ubuntu-latest
    steps:
    - name: Print something
      run: |
        echo hello

  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: x-danma/hello-world-composite-action@1.0.3
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

  job-d-reusable:
    name: job-d
    uses: x-danma/increment-semver-patch-and-tag-action/.github/workflows/reusable.yml@main
    with:
      config-path: .github/labeler.yml
