on:
  workflow_call:
    inputs:
        config-path:
          required: true
          type: string

jobs:
  job-a:
    name: job-c
    runs-on: ubuntu-latest
    steps:
    - name: Print something
      run: |
        echo hello
  
  hello_world_job:
    runs-on: windows-latest
    name: A job to say hello
    needs: job-a
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: x-danma/hello-world-composite-action@1.0.3
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash