on:
  push:
    tags:
      - '*'

jobs:
  deploy_dev-preview:
    runs-on: windows-latest
    name: deploy_dev-preview
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: x-danma/hello-world-composite-action@1.0.3
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
  
  deploy_dev:
    runs-on: windows-latest
    name: deploy_dev
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: x-danma/hello-world-composite-action@1.0.3
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

  deploy_prod-preview:
    runs-on: windows-latest
    name: deploy_prod-preview
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: x-danma/hello-world-composite-action@1.0.3
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

  deploy_prod:
    runs-on: windows-latest
    name: deploy_prod
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: x-danma/hello-world-composite-action@1.0.3
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash